In [1]:
import numpy as np
x=np.array([-1,0,1])

In [16]:
def sigmoid(x):
    """
    Compute the sigmoid function for the input here.
    """
    #if type(x) == list:
    x=np.array(x)
    return 1/(np.exp(-x)+1)


In [17]:
sigmoid(x)

array([ 0.26894142,  0.5       ,  0.73105858])

In [18]:
sigmoid([1,2,3])

array([ 0.73105858,  0.88079708,  0.95257413])

In [13]:
type([1,2])==list

True

In [15]:
sigmoid(1)

0.7310585786300049

In [21]:
x=np.array([[-1,0,1],[2,3,4]])

In [23]:
x

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [51]:
x=x-np.max(x)

In [52]:
x

array([[-5, -4, -3],
       [-2, -1,  0]])

In [57]:
x_exp=np.exp(x)
x_exp

array([[ 0.00673795,  0.01831564,  0.04978707],
       [ 0.13533528,  0.36787944,  1.        ]])

In [61]:
x_sum=np.sum(x_exp,axis=1).reshape(len(c),1)
x_sum

array([[ 0.07484065],
       [ 1.50321472]])

In [62]:
res=x_exp/x_sum

In [63]:
res

array([[ 0.09003057,  0.24472847,  0.66524096],
       [ 0.09003057,  0.24472847,  0.66524096]])

In [64]:
np.sum(res,axis=1)

array([ 1.,  1.])

In [65]:
m,n=x.shape

In [66]:
m

2

In [67]:
n

3

In [68]:
x.shape

(2, 3)

In [69]:
y=np.array([2,3,5])

In [70]:
y.shape

(3,)

In [76]:
m=y.shape[0]

m

In [77]:
m

3

In [80]:
z=np.array([[2],[5]])

In [81]:
z

array([[2],
       [5]])

In [82]:
z.shape

(2, 1)

In [92]:
x=np.array([[3.0,4.0],[1, 2]])
x


array([[ 3.,  4.],
       [ 1.,  2.]])

In [87]:
x = x / np.linalg.norm(x)
x

array([[ 0.54772256,  0.73029674],
       [ 0.18257419,  0.36514837]])

In [88]:
x=np.array([3,4])

In [100]:
x=np.array([[3.0,4.0],[1, 2]])
x

array([[ 3.,  4.],
       [ 1.,  2.]])

In [101]:
x = x / np.linalg.norm(x,axis=1)
x

array([[ 0.6       ,  1.78885438],
       [ 0.2       ,  0.89442719]])

In [2]:
import random
import numpy as np
from cs224d.data_utils import *
import matplotlib.pyplot as plt

from q3_word2vec import *
from q3_sgd import *

# Reset the random seed to make sure that everyone gets the same results
random.seed(314)
dataset = StanfordSentiment()
tokens = dataset.tokens()
nWords = len(tokens)

In [7]:
nWords

19539

In [8]:
# We are going to train 10-dimensional vectors for this assignment
dimVectors = 10

# Context size
C = 5


In [9]:
#初始化
random.seed(31415)
np.random.seed(9265)
#input初始化为小数，output初始化为0,why？
wordVectors = np.concatenate(((np.random.rand(nWords, dimVectors) - .5) / dimVectors, np.zeros((nWords, dimVectors))), axis=0)

In [10]:
wordVectors.shape

(39078, 10)

In [ ]:
#训练
wordVectors0 = sgd(lambda vec: word2vec_sgd_wrapper(skipgram, tokens, vec, dataset, C, 
                                                    negSamplingCostAndGradient),wordVectors, 
                   0.3, 40000, None, True, PRINT_EVERY=10)



In [22]:
tokens['sl2']

962

In [23]:
start_iter, oldx, state = load_saved_params()

In [26]:
state

In [81]:
 for iter in range(0 + 1, 10 + 1):
        print iter

1
2
3
4
5
6
7
8
9
10


In [28]:
len(dataset.allSentences())

299622

In [29]:
dataset.sampleTokenIdx()

21

In [67]:
centerword, context = dataset.getRandomContext(2)

In [68]:
centerword

'that'

In [69]:
context

[',', 'suspecting', 'improvised', 'on']

In [36]:
help( dataset.getRandomContext)

Help on method getRandomContext in module cs224d.data_utils:

getRandomContext(self, C=5) method of cs224d.data_utils.StanfordSentiment instance



In [70]:
x=np.array([[2,3,4],[1,4,5]])

In [80]:
x[1:2]

array([[1, 4, 5]])

In [82]:
v=x[1:2,:].T

In [83]:
v

array([[1],
       [4],
       [5]])

In [84]:
u=np.array([1,2,3])

In [85]:
u.shape

(3,)

In [87]:
u.dot(v)

array([24])

In [88]:
u

array([1, 2, 3])

In [89]:
3*u

array([3, 6, 9])

In [94]:
i=0
while i<10:
    a=np.random.randint(3)
    i+=1

In [95]:
a

2